// Run from D:\jobber-perfect\frontend
// node write-profile.js
const fs = require('fs');
const path = require('path');

const lines = [];
const p = (s) => lines.push(s);

p(`import { useState } from 'react';`);
p(`import { useAppStore, selectUser } from '../store/appStore';`);
p(`import { applyTheme } from '../hooks/useTheme';`);
p(``);
p(`const API_URL = 'https://web-production-8a8e1.up.railway.app/api';`);
p(``);
p(`const THEMES = [`);
p(`  { id: 'dark', label: 'Midnight Dark', icon: '🌑', swatches: ['#0a0a0a','#111111','#f97316'] },`);
p(`  { id: 'crimson',  label: 'Crimson',        icon: '🔴',  swatches: ['#0d0005','#130008','#f43f5e'] },`);
p(`  { id: 'nord',     label: 'Nord',           icon: '🧊',  swatches: ['#191d2b','#232938','#88c0d0'] },`);
p(`  { id: 'matrix',   label: 'Matrix Green',   icon: '💚',  swatches: ['#0d0d0d','#111','#00ff41'] },`);
p(`  { id: 'ocean',    label: 'Ocean Blue',     icon: '🌊',  swatches: ['#060d1a','#0d1b2e','#38bdf8'] },`);
p(`  { id: 'dusk',     label: 'Dusk',           icon: '🌆',  swatches: ['#13101e','#1e1530','#a78bfa'] },`);
p(`];`);
p(``);
p(`const SECTIONS = [`);
p(`  { id: 'overview',     label: 'Overview',     icon: '◈' },`);
p(`  { id: 'subscription', label: 'Subscription', icon: '◆' },`);
p(`  { id: 'security',     label: 'Security',     icon: '⬡' },`);
p(`  { id: 'preferences',  label: 'Preferences',  icon: '◉' },`);
p(`  { id: 'about',        label: 'About',        icon: '◎' },`);
p(`];`);
p(``);
p(`function InputRow({ label, value, onChange, show, onToggleShow, placeholder }: {`);
p(`  label: string; value: string; onChange: (v: string) => void;`);
p(`  show?: boolean; onToggleShow?: () => void; placeholder?: string;`);
p(`}) {`);
p(`  return (`);
p(`    <div style={{ marginBottom: 14 }}>`);
p(`      <div style={{ fontSize: 11, color: '#6b7280', marginBottom: 5, textTransform: 'uppercase', letterSpacing: '0.08em' }}>{label}</div>`);
p(`      <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>`);
p(`        <input`);
p(`          value={value}`);
p(`          onChange={e => onChange(e.target.value)}`);
p(`          type={show !== undefined ? (show ? 'text' : 'password') : 'password'}`);
p(`          placeholder={placeholder || ''}`);
p(`          maxLength={6}`);
p(`          style={{`);
p(`            flex: 1, background: '#0d0d0d', border: '1px solid #222',`);
p(`            borderRadius: 6, padding: '8px 10px', color: '#f1f5f9',`);
p(`            fontSize: 14, outline: 'none', fontFamily: 'JetBrains Mono, monospace',`);
p(`            letterSpacing: show ? '0.12em' : '0.3em',`);
p(`          }}`);
p(`        />`);
p(`        {onToggleShow && (`);
p(`          <button onClick={onToggleShow} title={show ? 'Hide' : 'Show'} style={{`);
p(`            background: '#111', border: '1px solid #222', borderRadius: 6,`);
p(`            padding: '8px 10px', color: show ? '#f97316' : '#4b5563',`);
p(`            cursor: 'pointer', fontSize: 14, lineHeight: 1,`);
p(`          }}>{show ? '🙈' : '👁'}</button>`);
p(`        )}`);
p(`      </div>`);
p(`    </div>`);
p(`  );`);
p(`}`);
p(``);
p(`function Stat({ label, value, accent }: { label: string; value: string; accent?: boolean }) {`);
p(`  return (`);
p(`    <div style={{ background: '#0d0d0d', border: '1px solid #1a1a1a', borderRadius: 8, padding: '14px 16px', flex: 1, minWidth: 120 }}>`);
p(`      <div style={{ fontSize: 11, color: '#4b5563', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>{label}</div>`);
p(`      <div style={{ fontSize: 16, fontWeight: 700, color: accent ? '#f97316' : '#f1f5f9', fontFamily: 'JetBrains Mono, monospace' }}>{value}</div>`);
p(`    </div>`);
p(`  );`);
p(`}`);
p(``);
p(`function Overview({ user }: { user: any }) {`);
p(`  const initials = (user?.name || user?.mobile || 'U').slice(0, 2).toUpperCase();`);
p(`  return (`);
p(`    <div>`);
p(`      <div style={{ display: 'flex', alignItems: 'center', gap: 20, marginBottom: 28 }}>`);
p(`        <div style={{`);
p(`          width: 64, height: 64, borderRadius: '50%',`);
p(`          background: 'linear-gradient(135deg,#f97316,#dc2626)',`);
p(`          display: 'flex', alignItems: 'center', justifyContent: 'center',`);
p(`          fontSize: 22, fontWeight: 800, color: '#fff', flexShrink: 0,`);
p(`          boxShadow: '0 0 0 3px #1a1a1a, 0 0 0 5px #f9731640',`);
p(`        }}>{initials}</div>`);
p(`        <div>`);
p(`          <div style={{ fontSize: 20, fontWeight: 700, color: '#f1f5f9' }}>{user?.name || 'Trader'}</div>`);
p(`          <div style={{ fontSize: 13, color: '#4b5563', marginTop: 3 }}>+91 {user?.mobile || '—'}</div>`);
p(`          <div style={{`);
p(`            display: 'inline-block', marginTop: 6, padding: '2px 10px',`);
p(`            background: '#f97316', borderRadius: 99, fontSize: 11,`);
p(`            fontWeight: 700, color: '#000', textTransform: 'uppercase', letterSpacing: '0.1em',`);
p(`          }}>Active</div>`);
p(`        </div>`);
p(`      </div>`);
p(`      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>`);
p(`        <Stat label="Plan" value="Jobber Pro" accent />`);
p(`        <Stat label="Member since" value="Mar 2026" />`);
p(`        <Stat label="Status" value="Verified" />`);
p(`      </div>`);
p(`    </div>`);
p(`  );`);
p(`}`);
p(``);
p(`function Subscription() {`);
p(`  return (`);
p(`    <div>`);
p(`      <div style={{`);
p(`        background: 'linear-gradient(135deg,#1a0f00,#0f0800)',`);
p(`        border: '1px solid #f9731620', borderRadius: 10, padding: 20, marginBottom: 20,`);
p(`      }}>`);
p(`        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>`);
p(`          <div>`);
p(`            <div style={{ fontSize: 11, color: '#f97316', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 6 }}>Current Plan</div>`);
p(`            <div style={{ fontSize: 24, fontWeight: 800, color: '#f1f5f9' }}>Jobber Pro</div>`);
p(`            <div style={{ fontSize: 13, color: '#6b7280', marginTop: 4 }}>Full options analytics access</div>`);
p(`          </div>`);
p(`          <div style={{ background: '#f97316', borderRadius: 6, padding: '4px 12px', fontSize: 12, fontWeight: 700, color: '#000' }}>ACTIVE</div>`);
p(`        </div>`);
p(`        <div style={{ height: 1, background: '#1f1f1f', margin: '16px 0' }} />`);
p(`        <div style={{ display: 'flex', gap: 20, flexWrap: 'wrap' }}>`);
p(`          {['VPIN Signal','OBI-L1','Options Chain','Spoofing Detector','Live Greeks'].map(f => (`);
p(`            <div key={f} style={{ fontSize: 12, color: '#9ca3af' }}>`);
p(`              <span style={{ color: '#22c55e', marginRight: 5 }}>✓</span>{f}`);
p(`            </div>`);
p(`          ))}`);
p(`        </div>`);
p(`      </div>`);
p(`      <div style={{ background: '#0d0d0d', border: '1px solid #1a1a1a', borderRadius: 8, padding: '14px 16px' }}>`);
p(`        <div style={{ fontSize: 12, color: '#6b7280' }}>For billing enquiries contact <span style={{ color: '#f97316' }}>support@optionslab.in</span></div>`);
p(`      </div>`);
p(`    </div>`);
p(`  );`);
p(`}`);
p(``);
p(`function Security({ user }: { user: any }) {`);
p(`  const [cur, setCur]     = useState('');`);
p(`  const [next, setNext]   = useState('');`);
p(`  const [confirm, setCnf] = useState('');`);
p(`  const [showCur, setSC]  = useState(false);`);
p(`  const [showNxt, setSN]  = useState(false);`);
p(`  const [showCnf, setSD]  = useState(false);`);
p(`  const [status, setStatus] = useState<{ ok: boolean; msg: string } | null>(null);`);
p(`  const [loading, setLoading] = useState(false);`);
p(``);
p(`  const handleChange = async () => {`);
p(`    setStatus(null);`);
p(`    if (!cur || !next || !confirm) return setStatus({ ok: false, msg: 'All fields are required.' });`);
p(`    if (!/^\\d{6}$/.test(next)) return setStatus({ ok: false, msg: 'New MPIN must be exactly 6 digits.' });`);
p(`    if (next !== confirm) return setStatus({ ok: false, msg: 'New MPIN and confirm do not match.' });`);
p(`    setLoading(true);`);
p(`    try {`);
p(`      const res = await fetch(API_URL + '/auth/change-mpin', {`);
p(`        method: 'POST',`);
p(`        headers: { 'Content-Type': 'application/json' },`);
p(`        body: JSON.stringify({ mobile: user?.mobile, currentMpin: cur, newMpin: next }),`);
p(`      });`);
p(`      const data = await res.json();`);
p(`      if (data.success) {`);
p(`        setStatus({ ok: true, msg: 'MPIN updated successfully.' });`);
p(`        setCur(''); setNext(''); setCnf('');`);
p(`      } else {`);
p(`        setStatus({ ok: false, msg: data.message || 'Update failed.' });`);
p(`      }`);
p(`    } catch {`);
p(`      setStatus({ ok: false, msg: 'Cannot reach server.' });`);
p(`    } finally {`);
p(`      setLoading(false);`);
p(`    }`);
p(`  };`);
p(``);
p(`  return (`);
p(`    <div>`);
p(`      <div style={{ fontSize: 13, color: '#6b7280', marginBottom: 20 }}>Change your 6-digit MPIN used to log in to Jobber Pro.</div>`);
p(`      <InputRow label="Current MPIN"     value={cur}     onChange={setCur}  show={showCur} onToggleShow={() => setSC(v => !v)} placeholder="------" />`);
p(`      <InputRow label="New MPIN"         value={next}    onChange={setNext} show={showNxt} onToggleShow={() => setSN(v => !v)} placeholder="------" />`);
p(`      <InputRow label="Confirm New MPIN" value={confirm} onChange={setCnf}  show={showCnf} onToggleShow={() => setSD(v => !v)} placeholder="------" />`);
p(`      {status && (`);
p(`        <div style={{`);
p(`          padding: '10px 14px', borderRadius: 7, marginBottom: 14, fontSize: 13,`);
p(`          background: status.ok ? '#052e16' : '#2d0a0a',`);
p(`          border: '1px solid ' + (status.ok ? '#16a34a' : '#7f1d1d'),`);
p(`          color: status.ok ? '#4ade80' : '#fca5a5',`);
p(`        }}>{status.msg}</div>`);
p(`      )}`);
p(`      <button onClick={handleChange} disabled={loading} style={{`);
p(`        background: loading ? '#333' : 'linear-gradient(90deg,#f97316,#dc2626)',`);
p(`        border: 'none', borderRadius: 7, padding: '10px 22px',`);
p(`        color: '#fff', fontSize: 13, fontWeight: 700, cursor: loading ? 'not-allowed' : 'pointer',`);
p(`        letterSpacing: '0.05em',`);
p(`      }}>{loading ? 'Updating…' : 'Update MPIN'}</button>`);
p(`    </div>`);
p(`  );`);
p(`}`);
p(``);
p(`function Preferences() {`);
p(`  const [active, setActive] = useState(localStorage.getItem('jp_theme') || 'dark');`);
p(`  const handleTheme = (id: string) => { applyTheme(id); setActive(id); };`);
p(`  return (`);
p(`    <div>`);
p(`      <div style={{ fontSize: 13, color: '#6b7280', marginBottom: 20 }}>Choose a visual theme. Applied instantly and saved across sessions.</div>`);
p(`      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>`);
p(`        {THEMES.map(t => {`);
p(`          const isActive = active === t.id;`);
p(`          return (`);
p(`            <button key={t.id} onClick={() => handleTheme(t.id)} style={{`);
p(`              background: isActive ? '#0f0700' : '#0a0a0a',`);
p(`              border: '1.5px solid ' + (isActive ? '#f97316' : '#1a1a1a'),`);
p(`              borderRadius: 10, padding: '14px 16px', cursor: 'pointer',`);
p(`              textAlign: 'left', transition: 'all 0.15s ease',`);
p(`              boxShadow: isActive ? '0 0 0 1px #f9731640' : 'none',`);
p(`            }}>`);
p(`              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>`);
p(`                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>`);
p(`                  <span style={{ fontSize: 16 }}>{t.icon}</span>`);
p(`                  <span style={{ fontSize: 13, fontWeight: 600, color: isActive ? '#f97316' : '#d1d5db' }}>{t.label}</span>`);
p(`                </div>`);
p(`                {isActive && <span style={{ color: '#f97316', fontSize: 16 }}>✓</span>}`);
p(`              </div>`);
p(`              <div style={{ display: 'flex', gap: 5 }}>`);
p(`                {t.swatches.map((c, i) => (`);
p(`                  <div key={i} style={{ width: 20, height: 20, borderRadius: 4, background: c, border: '1px solid #2a2a2a' }} />`);
p(`                ))}`);
p(`              </div>`);
p(`            </button>`);
p(`          );`);
p(`        })}`);
p(`      </div>`);
p(`    </div>`);
p(`  );`);
p(`}`);
p(``);
p(`function About() {`);
p(`  const rows: [string, string][] = [`);
p(`    ['Version',   'v2.0.0'],`);
p(`    ['Platform',  'Electron + React + Vite'],`);
p(`    ['Backend',   'Railway — Express + PostgreSQL'],`);
p(`    ['Data Feed', 'Angel One WebSocket (Live)'],`);
p(`    ['Support',   'support@optionslab.in'],`);
p(`  ];`);
p(`  return (`);
p(`    <div>`);
p(`      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 }}>`);
p(`        <div style={{`);
p(`          background: 'linear-gradient(135deg,#f97316,#dc2626)', borderRadius: 10,`);
p(`          padding: '10px 14px', fontSize: 20, fontWeight: 900, color: '#fff',`);
p(`          fontFamily: 'Bebas Neue, sans-serif', letterSpacing: '0.1em',`);
p(`        }}>JP</div>`);
p(`        <div>`);
p(`          <div style={{ fontSize: 18, fontWeight: 800, color: '#f1f5f9', fontFamily: 'Rajdhani, sans-serif' }}>JOBBER PRO</div>`);
p(`          <div style={{ fontSize: 12, color: '#4b5563' }}>Professional NIFTY Options Analytics</div>`);
p(`        </div>`);
p(`      </div>`);
p(`      {rows.map(([k, v]) => (`);
p(`        <div key={k} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid #111', fontSize: 13 }}>`);
p(`          <span style={{ color: '#6b7280' }}>{k}</span>`);
p(`          <span style={{ color: '#d1d5db' }}>{v}</span>`);
p(`        </div>`);
p(`      ))}`);
p(`    </div>`);
p(`  );`);
p(`}`);
p(``);
p(`export default function Profile({ onClose }: { onClose: () => void }) {`);
p(`  const user = useAppStore(selectUser);`);
p(`  const setUser = useAppStore(s => s.setUser);`);
p(`  const [section, setSection] = useState('overview');`);
p(``);
p(`  const handleLogout = () => {`);
p(`    try { localStorage.removeItem('optionlab_token'); localStorage.removeItem('optionlab_user'); } catch {}`);
p(`    setUser(null);`);
p(`    onClose();`);
p(`  };`);
p(``);
p(`  const renderSection = () => {`);
p(`    switch (section) {`);
p(`      case 'overview':     return <Overview user={user} />;`);
p(`      case 'subscription': return <Subscription />;`);
p(`      case 'security':     return <Security user={user} />;`);
p(`      case 'preferences':  return <Preferences />;`);
p(`      case 'about':        return <About />;`);
p(`      default:             return null;`);
p(`    }`);
p(`  };`);
p(``);
p(`  return (`);
p(`    <div style={{`);
p(`      position: 'fixed', inset: 0, zIndex: 9999,`);
p(`      background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(8px)',`);
p(`      display: 'flex', alignItems: 'center', justifyContent: 'center',`);
p(`    }}>`);
p(`      <div style={{`);
p(`        width: 640, maxWidth: '95vw', maxHeight: '88vh',`);
p(`        background: '#050505', border: '1px solid #1a1a1a',`);
p(`        borderRadius: 14, display: 'flex', flexDirection: 'column',`);
p(`        boxShadow: '0 25px 80px rgba(0,0,0,0.9), 0 0 0 1px #f9731615',`);
p(`        overflow: 'hidden',`);
p(`      }}>`);
p(`        <div style={{`);
p(`          display: 'flex', alignItems: 'center', justifyContent: 'space-between',`);
p(`          padding: '16px 22px', borderBottom: '1px solid #111', flexShrink: 0,`);
p(`        }}>`);
p(`          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>`);
p(`            <span style={{ fontSize: 16, color: '#f97316' }}>◈</span>`);
p(`            <span style={{ fontSize: 15, fontWeight: 700, color: '#f1f5f9', fontFamily: 'Rajdhani, sans-serif', letterSpacing: '0.05em' }}>ACCOUNT & PREFERENCES</span>`);
p(`          </div>`);
p(`          <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#4b5563', fontSize: 20, cursor: 'pointer', lineHeight: 1 }}>×</button>`);
p(`        </div>`);
p(`        <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>`);
p(`          <div style={{ width: 170, flexShrink: 0, borderRight: '1px solid #111', display: 'flex', flexDirection: 'column', padding: '12px 0' }}>`);
p(`            {SECTIONS.map(s => (`);
p(`              <button key={s.id} onClick={() => setSection(s.id)} style={{`);
p(`                background: section === s.id ? '#0f0700' : 'transparent',`);
p(`                border: 'none',`);
p(`                borderLeft: section === s.id ? '2px solid #f97316' : '2px solid transparent',`);
p(`                padding: '10px 18px', textAlign: 'left', cursor: 'pointer',`);
p(`                display: 'flex', alignItems: 'center', gap: 10, transition: 'all 0.1s',`);
p(`              }}>`);
p(`                <span style={{ fontSize: 14, color: section === s.id ? '#f97316' : '#374151' }}>{s.icon}</span>`);
p(`                <span style={{ fontSize: 13, fontWeight: section === s.id ? 600 : 400, color: section === s.id ? '#f1f5f9' : '#6b7280' }}>{s.label}</span>`);
p(`              </button>`);
p(`            ))}`);
p(`            <div style={{ flex: 1 }} />`);
p(`            <button onClick={handleLogout} style={{`);
p(`              background: 'transparent', border: 'none', borderLeft: '2px solid transparent',`);
p(`              padding: '10px 18px', textAlign: 'left', cursor: 'pointer',`);
p(`              display: 'flex', alignItems: 'center', gap: 10, color: '#ef4444', fontSize: 13,`);
p(`            }}>⏻ Log Out</button>`);
p(`          </div>`);
p(`          <div style={{ flex: 1, overflowY: 'auto', padding: '24px 26px' }}>`);
p(`            <div style={{ fontSize: 11, color: '#374151', textTransform: 'uppercase', letterSpacing: '0.12em', marginBottom: 18 }}>`);
p(`              {SECTIONS.find(s => s.id === section)?.label}`);
p(`            </div>`);
p(`            {renderSection()}`);
p(`          </div>`);
p(`        </div>`);
p(`      </div>`);
p(`    </div>`);
p(`  );`);
p(`}`);

const content = lines.join('\n');
const dest = path.join(__dirname, 'src', 'pages', 'Profile.tsx');
fs.writeFileSync(dest, content, 'utf8');
console.log('✅ Profile.tsx written — ' + lines.length + ' lines → ' + dest);